README.md, lib/jasmine-rails.rb, lib/jasmine_rails/runner.rb
The PhantomJS gem will automatically download and install a copy of
PhantomJS. The download and installation is over http and without a
checksum, which poses a security risk.
Maintains current default behaviour of downloading and will only skip
the download if the config option is set.
I believe this will resolve https://github.com/searls/jasmine-rails/issues/133
=> Add option to not use the PhantomJS gem executable

lib/generators/jasmine_rails/templates/jasmine.yml
Very minor change, but when adding a new item to the list my text editor
seems to get confused by the single space here.
=> Add another space to src_files list in jasmine.yml

README.md, lib/jasmine-rails.rb, lib/jasmine_rails/runner.rb
If someone want to pass a custom option to phantomjs executable, the only way is
making phantomjs gem optional. This PR adds a config `phantom_options` allowing
custom command-line options for phantom
=> Pass options to phantomjs executable

lib/jasmine-rails.rb
Hey humans,
It would be great if one could pass a custom yml file instead of the default one. Scenarios include having a separate `application.js` for legacy code and a current one.
If you do have a custom yml file then you would simply need to add the environment variable from the console before firing up the test from the web or otherwise.
`RAILS_ENV=test JASMINE_CONFIG=jasmine_legacy.yml bundle exec rake spec:javascript`
or 
`JASMINE_CONFIG=jasmine_legacy.yml bundle exec rails server`
WDYT?
=> Allow passing config yaml file name from environment

gemfiles/rails-3.2, lib/tasks/jasmine-rails_tasks.rake
Addresses searls/jasmine-rails#121 - In brief, a recurring source of issues has been forgetting to set `RAILS_ENV` to `test` before running the `spec:javascript` task. This is an implementation of a solution proposed in the issue discussion, namely a guard check to see if the environment is correct and (if it isn't) launch the task again in the correct environment.
=> Ensure `RAILS_ENV` is set to `test` when running tests

app/views/layouts/jasmine_rails/spec_runner.html.erb
Without this, IE9 would run in quirks mode, giving IE8-type "isArray" errors with React.
More details: http://stackoverflow.com/a/29828955/6962
=> spec_runner: target the current version of IE

lib/tasks/jasmine-rails_tasks.rake
We recently picked up the 0.12.0 branch.  I noticed that you merged in this fix by @rudyjahchan https://github.com/searls/jasmine-rails/commit/4691ac7c9554eb49c3867c8223e4a9f5e74f511f with the tiny change hands the full set of ARGV to rake.   That seems a little strange given that this task is supposed to be running only the javascript tests so if I run rake with any other tasks included, they'll get run twice.
`rake spec spec:javascripts`
will run the `spec` task twice before running `spec:javascripts`.
I also found that the exit code is not preserved so if you were counting on this command to trigger something else (while not in test mode) like
`rake spec spec:javascripts && cap deploy acceptance`
this would deploy code even if the JS tests failed.  
This commit adjusts the rake call in …
=> preserve exit code when running specs in non-test env

lib/tasks/jasmine-rails_tasks.rake
fix weird behaviour for jruby - output disappear from screen
appear on jruby 1.7.16.1 only when you type bundle exec spec:javascript
without RAILS_ENV=test in the begining. with RAILS_ENV=test it working..
Resolves #177
=> JRuby issue fix for bundle exec spec:javascript

lib/assets/javascripts/jasmine-runner.js, spec/jasmine_spec.rb
Currently, using jasmine-rails with phantomjs 2.1.1 causes phantomjs to
segfault. It appears that the onInitialized handler registered in
libe/assets/javascripts/jasmine-runner.js:48 is being executed multiple
times. Each call registers a window.onLoad listener which eventually
calls phantom.exit. It is unclear why page.onInitialized is called more
than once.
This commit introduces an initialized flag which prevents the
page.onInitialized callback from registering more than one window.onLoad
callback.
Not an ideal fix. It would be better to figure out what causes
page.onInitialized to be executed multiple times.
=> Prevent multiple calls to phantom.exit

lib/jasmine_rails/offline_asset_paths.rb
Warning: this produces a jillion deprecation warnings. Those are tracked by #187
In order to fix the deprecation warnings safely, we need to get rails 5 into the test matrix ( #188)
Resolves #185
=> Fix Rails 5

lib/assets/javascripts/jasmine-runner.js
http://stackoverflow.com/questions/24436460
https://github.com/ariya/phantomjs/issues/10357
https://github.com/ariya/phantomjs/commit/5768b705a0
Without this change, PhantomJS 2 consumes all available memory (at least 8 GB) with our test suite.
=> Work around PhantomJS 2 memory consumption issue

lib/jasmine-rails.rb
The version check might be unnecessary - this might be safe to do on earlier versions of Sprockets, too. But I know leaving the extensions works up through Sprockets 3, and I don't have quick access to a Sprockets 2 test environment.
=> Fix JasmineRails.spec_files for Sprockets 4

lib/jasmine-rails.rb, run-tests.rb, spec/javascripts/support/jasmine.yml
* For consistency with other config options that allow globbing (e.g. `helpers`, `spec_files`)
* To make it easier to add spec directories that follow a common naming convention (e.g. in engines)
=> Allow globbing in spec_dir in jasmine.yml

lib/jasmine_rails/runner.rb
Removes deprecations of the form:
```
DEPRECATION WARNING: ActionDispatch::IntegrationTest HTTP request
methods will accept only
the following keyword arguments in future Rails versions:
params, headers, env, xhr, as
Examples:
get '/profile',
params: { id: 1 },
headers: { 'X-Extra-Header' => '123' },
env: { 'action_dispatch.custom' => 'custom' },
xhr: true,
as: :json
```
=> Remove Rails 5 request spec params deprecation

lib/tasks/jasmine-rails_tasks.rake
Updated `rake spec:javascript` so it doesn't short circuit a chain of rake tasks by using `exec`.
Fixes https://github.com/searls/jasmine-rails/issues/199
=> Updated `rake spec:javascript` so it doesn't short circuit

lib/jasmine_rails/offline_asset_paths.rb, lib/jasmine_rails/runner.rb
**Continuing #202 here with the 1.9 builds included**
Closes #187 
`#alias_method_chain` is deprecated in Rails 5. Use Ruby 2's `#prepend` instead.
AFAIK this should cap off Rails 5 support with #198. The other warnings in the related issue I assume are just from the example app.
I do not use jasmine-rails, so I would recommend someone with a bit more knowledge actually give this a try - especially with Rails 3, as I just checked the 3.2 stable branch and noted the class/method name change that was done from that version. Also I'm not sure what `Sprockets::Rails::Helper` actually referred to. But I believe it was being included somewhere else anyway (Probably Base), so a prepend to that won't work anymore anyway, hence my use of Base.
=> Remove alias_method_chains for OfflineAssetPaths

lib/jasmine-rails.rb
Running `bin/rails test -w` exposed
`warning: File.exists? is a deprecated name, use File.exist?`
=> Use File.exist? instead of File.exists?

README.md, lib/jasmine-rails.rb, lib/jasmine_rails/runner.rb
Currently it doesn't work. See #192 
```yml
phantom_options: --debug=true --web-security=false
```
=> Allow to pass several options to PhantomJS via jasmine.yml. Fix #192

.travis.yml, CHANGELOG.md
With so many typical Rails app deps moving to drop pre-2.0 rubies, keeping on top of the (intentionally loose) Gemfiles used for the multi-matrix build has become too much of a burden for what we get out of it.
This PR drops 1.9 from the CI build and with it any official "support" insofar as we expect to be on top of any changes that break 1.9--we'll still gladly accept patches that keep it on life support, though, and this shouldn't be taken as indication that post-0.14.2 releases are necessarily broken on 1.9
=> Drop official Ruby 1.9 support

lib/jasmine_rails/offline_asset_paths.rb
Fixes https://github.com/searls/jasmine-rails/issues/213
The JasmineRails::OfflineAssetPaths monkey patch of `compute_asset_path` has a Rails 3 signature:
https://github.com/searls/jasmine-rails/blob/master/lib/jasmine_rails/offline_asset_paths.rb#L9
This was updated from 3 arguments to 2 in Rails 4:
Rails 3: https://apidock.com/rails/ActionView/AssetPaths/compute_public_path
Rails 4: https://apidock.com/rails/ActionView/Helpers/AssetUrlHelper/compute_asset_path
If JasmineRails::OfflineAssetPaths.disabled is true, then the method is meant to shortcut and run the original super method. This gave an error like:
```
ActionView::Template::Error: wrong number of arguments (given 3, expected 1..2)
```
cc @h-lame
=> Update compute_asset_path to Rails 4 signature

lib/assets/javascripts/jasmine-runner.js
It seams that onError catches console.error and this create a circular invokation.
Maybe we could redirect all in stdout, this is a solution and works well
=> always use console log instead of error

.travis.yml
This would fix the Rails 4 builds on Travis, but freezing turbolinks on 5.0 would also fix it.
I'm not an expert here, but I predict going forward is the right thing to do.
=> Update Travis to Ruby 2.1

.travis.yml, gemfiles/rails-3.2, gemfiles/rails-5-sprockets-4, gemfiles/rails-5.0
Travis is failing on rails 5.0 and rails 5-sprockets-4 variants because of a missing puma from the Gemfile.
=> fix travis on rails-5.0 and rails-5-sprockets-4

lib/jasmine_rails/runner.rb
`DEPRECATION WARNING: The success? predicate is deprecated and will be removed in Rails 6.0. Please use successful? as provided by Rack::Response::Helpers.`
(this is equivalent to #229 but rebased on master)
=> fix deprecation warning on Rails 5.2
